
###########################################################
#
# ****** PHYSICAL PROCESES
#
/gate/physics/addPhysicsList emstandard

# *** default 0.1 keV - 100 TeV
##/gate/physics/setEMin 0.1 keV
##/gate/physics/setEMax 10 MeV
##/gate/physics/processList Enabled
##/gate/physics/processList Initialized




/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess MultipleScattering e+
/gate/physics/addProcess MultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
# **************CUTS***********
#
/gate/physics/Gamma/SetCutInRegion      world 10  mm
/gate/physics/Electron/SetCutInRegion   world 10  mm
/gate/physics/Positron/SetCutInRegion   world 10  mm

/gate/physics/Gamma/SetCutInRegion      det0 1 mm
/gate/physics/Electron/SetCutInRegion   det0 1 mm
/gate/physics/Positron/SetCutInRegion   det0 1 mm
/gate/physics/SetMaxStepSizeInRegion    det0 1 mm
#
#/gate/physics/Gamma/SetCutInRegion      polyphantom 0.1 mm
#/gate/physics/Electron/SetCutInRegion   polyphantom 0.1 mm
#/gate/physics/Positron/SetCutInRegion   polyphantom 0.1 mm
#/gate/physics/SetMaxStepSizeInRegion    polyphantom 0.1 mm


#############################################################


